# Generated by Django 3.1 on 2023-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productviewbyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('product_id_list', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
